### 1~3 개별 전처리 후 , pickle 또는 csv저장
1. 전국일방통행도로표준데이터
    * 시도명, 지정사유, 지정연도, 도로폭, 도로차로수,보차분리여부
    
2. 전국 어린이보호구역표준데이터 시도명 작업필요
    * 시설종류, 관할경찰서명, CCTV설치여부, CCTV설치대수, 제공기관명, 보호구역도로폭
    
3. 전국노인장애인보호구역표준데이터
    * 시도명, 제한속도,CCTV설치여부,CCTV설치대수,보호구역도로폭
4. 새로운 jupyter note에서 종합 
    * 시도명, 어린이보호구역 CCTV설치대수,노인장애인보호구역 CCTV설치대수, 일방통행 보차분리 ycount

In [3]:
import numpy as np
import pandas as pd

In [4]:
raw_data = pd.read_csv('전국노인장애인보호구역표준데이터.csv', encoding = 'cp949')
column_s = ['시도명','제한속도','CCTV설치여부','CCTV설치대수','보호구역도로폭']
pd_data = raw_data[column_s]
pd_data

        시도명  제한속도 CCTV설치여부  CCTV설치대수 보호구역도로폭
0     서울특별시    30        Y       1.0       3
1      경상북도    30        N       NaN       6
2      경상북도    30        N       NaN       6
3      경상북도    30        N       NaN       7
4      경상북도    30        N       NaN       7
...     ...   ...      ...       ...     ...
2513  대구광역시    30        N       NaN     NaN
2514  대구광역시    30        N       NaN     NaN
2515  대구광역시    30        N       NaN     NaN
2516  대구광역시    30        N       NaN     NaN
2517  대구광역시    30        N       NaN     NaN

[2518 rows x 5 columns]

In [18]:
print(pd_data.shape)
print(pd_data.dtypes)
print('****************************')
for e in pd_data:
    print(e,'\t', pd_data[e].hasnans)

(2518, 5)
시도명          object
제한속도          int64
CCTV설치여부     object
CCTV설치대수    float64
보호구역도로폭      object
dtype: object
****************************
시도명 	 False
제한속도 	 False
CCTV설치여부 	 False
CCTV설치대수 	 True
보호구역도로폭 	 True

In [11]:
#시도명
print(pd_data['시도명'].unique())
print(pd_data['시도명'].hasnans)

['서울특별시' '경상북도' '충청남도' '강원도' '경기도' '전라북도' '대전광역시' '경상남도' '인천광역시' '울산광역시'
 '부산광역시' '대구광역시' '충청북도' '전라남도' '광주광역시' '세종특별자치시' '제주특별자치도']
False

In [9]:
col = pd_data['제한속도']
print(col.unique(),col.hasnans)
print(col.describe())

[30 50 60 40 38 39 41 42 43 44 45 46 47 48 49 51 52 53 54 55 31 32 33 34
 35 36 37 20] False
count    2518.000000
mean       31.098094
std         4.649784
min        20.000000
25%        30.000000
50%        30.000000
75%        30.000000
max        60.000000
Name: 제한속도, dtype: float64

In [15]:
print(pd_data['CCTV설치여부'].unique())
print(pd_data['CCTV설치여부'].hasnans)

['Y' 'N']
False

In [11]:

print(pd_data['CCTV설치대수'].unique())
print(pd_data['CCTV설치대수'].hasnans)
#결측지 nan - > 0 으로 변환
yfilter = pd_data['CCTV설치여부'] == 'Y'
nfilter = pd_data['CCTV설치여부'] == 'N'
pd_data.loc[yfilter, 'CCTV설치대수'] = pd_data.loc[yfilter,'CCTV설치대수'].fillna(1.0)
pd_data.loc[nfilter, 'CCTV설치대수'] = pd_data.loc[nfilter,'CCTV설치대수'].fillna(0.0)
pd_data

[ 1. nan  0.  2.  4.  3.  5.  8.  9.]
True

        시도명  제한속도 CCTV설치여부  CCTV설치대수 보호구역도로폭
0     서울특별시    30        Y       1.0       3
1      경상북도    30        N       0.0       6
2      경상북도    30        N       0.0       6
3      경상북도    30        N       0.0       7
4      경상북도    30        N       0.0       7
...     ...   ...      ...       ...     ...
2513  대구광역시    30        N       0.0     NaN
2514  대구광역시    30        N       0.0     NaN
2515  대구광역시    30        N       0.0     NaN
2516  대구광역시    30        N       0.0     NaN
2517  대구광역시    30        N       0.0     NaN

[2518 rows x 5 columns]

In [38]:
print(pd_data['보호구역도로폭'].unique())
print(pd_data['보호구역도로폭'].hasnans)
print(pd_data['보호구역도로폭'].isna().value_counts())

def fu1(x):
    if(x == np.NaN) or (type(x) == type(1.0)):
        return x
    if '~' in x:
        return np.mean(np.arrat(x.split('~')).astype(np.float64))
    else:
        return float(x)

['3' '6' '7' '8' '9' nan '7.5' '6.5' '15' '11' '4' '20' '12' '13' '28'
 '20~34' '10' '15~20' '24' '25' '5' '14' '6~12' '16' '17~22' '4.5~5' '4.5'
 '20~23' '6~8' '33' '30' '12~13' '10~12' '8~9' '9~10' '4~30' '7~12' '35'
 '9.6~14.6' '14~25' '12~20' '21' '5~20' '1' '6~14' '5~7' '5~6' '7~11'
 '8~20' '4~8' '4~7' '18' '16~20' '5.5' '23' '6~10' '10~30' '6~7' '8~10'
 '36' '6~25' '22' '5.2' '10~15' '8.5' '6.5~12' '5~10' '0' '29' '5~8' '5~9'
 '33~35' '8 ~25' '7~9' '13~14' '5~11' '5~30' '5~15' '10~14' '26' '7~8'
 '4.5~6.5' '18~36' '5~16' '17' '10~35' '19' '8~12' '6~9' '7.5~12' '4~8.5'
 '5.0~11' '7.5~8' '8.5~25' '8.5~11' '6~13' '7~10' '40' '8~14' '20~30'
 '3~5' '8~35' '12~16' '13~15' '7~15' '5.7' '8.4' '3~4' '6.3~14.8' '2' 0]
True
False    1485
True     1034
Name: 보호구역도로폭, dtype: int64

C:\Users\ITPS\AppData\Local\Temp\ipykernel_4792\1010988455.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pd_data['보호구역도로폭'] = pd_data['보호구역도로폭'].dropna()

In [39]:
pd_data

            시도명  제한속도 CCTV설치여부  CCTV설치대수 보호구역도로폭
0         서울특별시    30        Y       1.0       3
1          경상북도    30        N       0.0       6
2          경상북도    30        N       0.0       6
3          경상북도    30        N       0.0       7
4          경상북도    30        N       0.0       7
...         ...   ...      ...       ...     ...
2514      대구광역시    30        N       0.0     NaN
2515      대구광역시    30        N       0.0     NaN
2516      대구광역시    30        N       0.0     NaN
2517      대구광역시    30        N       0.0     NaN
CCTV설치대수      0     0        0       0.0       0

[2519 rows x 5 columns]