In [80]:
import seaborn as sns
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib

current_font_list = matplotlib.rcParams['font.family']
font_path = "C:\Windows\Fonts\gulim.ttc"
kfont = matplotlib.font_manager.FontProperties(fname=font_path).get_name()

matplotlib.rcParams['font.family'] = [kfont] + current_font_list

df1 = pd.read_csv('이륜차신고현황_시도별_행렬전환.csv', encoding='cp949', header=[0,1])
df1.drop(('시도명(1)','시도명(1)'),axis=1, inplace=True)
# print(df1)
# print(df1[('계' '경형')])
df2 = pd.read_csv('이륜차신고현황_시도별_20230310150634.csv', encoding='cp949', header=[0,1,2])
df2.drop(('시도명(1)','시도명(1)','시도명(1)'),axis=1, inplace=True)
df2.columns.names = ['시점','소유','크기']
# print(df2.columns)
# print(df2)
# df2.stack(level=0)
a = df2.set_index(('시군구(1)','시군구(1)','시군구(1)'))
b = a.stack(level=0)
b.index.names=['지역','시점']
c = b.swaplevel(0,1)
d = c.stack(level=0)
d.reset_index(inplace=True)
d.insert(0,'년',d['시점'].apply(lambda x: str(x).split('.')[0]))
d.insert(1,'월',d['시점'].apply(lambda x: str(x).split('.')[1]))
d

크기     년   월       시점    지역   소유   경형    대형     소계    소형     중형
0   2023  01  2023.01   강서구   관용    3     0     51     8     40
1   2023  01  2023.01   강서구  자가용  361   552   5868  1787   3168
2   2023  01  2023.01    중구   관용    0     0     89    20     69
3   2023  01  2023.01    중구  자가용   99   141   2928   658   2030
4   2023  01  2023.01   금정구   관용    5     2     79     4     68
5   2023  01  2023.01   금정구  자가용  345   573   8096  2068   5110
6   2023  01  2023.01   기장군   관용    2     0     68     8     58
7   2023  01  2023.01   기장군  자가용  309   627   5818  1465   3417
8   2023  01  2023.01    남구   관용    3     0     31    10     18
9   2023  01  2023.01    남구  자가용  448   941  10733  2398   6946
10  2023  01  2023.01    동구   관용    2     1     57    22     32
11  2023  01  2023.01    동구  자가용  183   320   4421   941   2977
12  2023  01  2023.01   동래구   관용    1     1     74     1     71
13  2023  01  2023.01   동래구  자가용  403   854   8902  2132   5513
14  2023  01  2023.01  부산진구   관용   10     1    118    21     86
15  2023  01  2023.01  부산진구  자가용  623  1396  15928  3901  10008
16  2023  01  2023.01    북구   관용    1     0     50     4     45
17  2023  01  2023.01    북구  자가용  413   720   8691  2071   5487
18  2023  01  2023.01   사상구   관용   26     1    161    38     96
19  2023  01  2023.01   사상구  자가용  550   602   9283  2238   5893
20  2023  01  2023.01   사하구   관용    6     0     80     2     72
21  2023  01  2023.01   사하구  자가용  522   969  12473  2886   8096
22  2023  01  2023.01    서구   관용    1     0      9     6      2
23  2023  01  2023.01    서구  자가용  206   342   6059  1480   4031
24  2023  01  2023.01   수영구   관용    0     1     85     4     80
25  2023  01  2023.01   수영구  자가용  307   674   6666  1468   4217
26  2023  01  2023.01   연제구   관용    5    36    134     4     89
27  2023  01  2023.01   연제구  자가용  274   645   6868  1587   4362
28  2023  01  2023.01   영도구   관용    5     0     50     2     43
29  2023  01  2023.01   영도구  자가용  216   344   6371  1480   4331
30  2023  01  2023.01  해운대구   관용    7     1     96     2     86
31  2023  01  2023.01  해운대구  자가용  537  1332  12695  2924   7902
32  2023  01  2023.01  부산기타   관용    0     0      0     0      0
33  2023  01  2023.01  부산기타  자가용    0     0     12    10      2

In [122]:
df3 = pd.read_csv('이륜차신고현황_시도별_서울.csv', encoding='cp949', header=[0,1,2])
df3.drop(('시도명(1)','시도명(1)','시도명(1)'), axis=1, inplace=True)
df3.columns.names=['시점','소유','크기']
a2 = df3.set_index(('시군구(1)','시군구(1)','시군구(1)'))
b2 = a2.stack(level=0)
b2.index.names=['지역','시점']
c2 = b2.swaplevel(0,1)
d2 = c2.stack(level=0)
d2.reset_index(inplace=True) 
d2.insert(0,'년',d2['시점'].apply(lambda x: str(x).split('.')[0])) 
d2.insert(1,'월',d2['시점'].apply(lambda x: str(x).split('.')[1]))


filter1 = d2['소유'] == '관용'
# filter2 = d2['소유'] == '자가용'
f1 = d2[filter1]
# f2 = d2[filter2]
f1

크기     년   월       시점    지역  소유  경형   대형  소형   중형
0   2023  01  2023.01   강남구  관용  23    3  58  235
2   2023  01  2023.01   강동구  관용  16    0  22  107
4   2023  01  2023.01   강북구  관용   7    1   2   33
6   2023  01  2023.01   강서구  관용   6    1  25  127
8   2023  01  2023.01   관악구  관용  11    2  96   93
10  2023  01  2023.01   광진구  관용   8    2  10  156
12  2023  01  2023.01   구로구  관용   8    1   2  183
14  2023  01  2023.01   금천구  관용   3    0  18   12
16  2023  01  2023.01   노원구  관용   1    1  24   80
18  2023  01  2023.01   도봉구  관용   3    1   6  133
20  2023  01  2023.01  동대문구  관용   4    1  19  156
22  2023  01  2023.01   동작구  관용   6    1  35   98
24  2023  01  2023.01   마포구  관용  10    4  20  134
26  2023  01  2023.01  서대문구  관용   2    0  34  114
28  2023  01  2023.01   서초구  관용  12   14  36  196
30  2023  01  2023.01   성동구  관용  59    1  29   13
32  2023  01  2023.01   성북구  관용   7    1  28  204
34  2023  01  2023.01   송파구  관용  17    1  58  129
36  2023  01  2023.01   양천구  관용  21    1  11   91
38  2023  01  2023.01  영등포구  관용  13    1  21  144
40  2023  01  2023.01   용산구  관용   6    1  48   97
42  2023  01  2023.01   은평구  관용  17    2  17  102
44  2023  01  2023.01   종로구  관용  13  115  39  264
46  2023  01  2023.01    중구  관용  23    2  55  136
48  2023  01  2023.01   중랑구  관용   6    1  17   93
50  2023  01  2023.01  서울기타  관용   0    0   0    0

In [ ]:
### 코로나 이전 (2014~2018)과 코로나 이후(2020~2023) 크키 비율이 다른가